# hive 数据源自定义配置
hive:
  url: jdbc:hive2://10.250.20.21:7432/default
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  username: hive
  password: hive
